apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""          # Bỏ StorageClass hoặc để rỗng để match với PVC manual
  hostPath:
    path: /mnt/data              # Ví dụ, hoặc thay bằng NFS/vStorage gì bạn dùng

