apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
  namespace: rag-system
data:
  # ✅ OpenSearch Configuration
  OPENSEARCH_URL: "https://khuongnd3-opens-107444-344gj-hcm03.vdb-opensearch.vngcloud.vn:9200"
  OPENSEARCH_INDEX: "rag-assistant"

  # ✅ Ollama Configuration
  OLLAMA_URL: "http://ollama-service.rag-system.svc.cluster.local:11434"
  OLLAMA_MODEL: "deepseek-r1:8b"

  # ✅ Embedding
  EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"

  # ✅ RAG Settings
  RAG_TOP_K: "5"
  chunk_size: "1000"
  chunk_overlap: "200"

  # ✅ VNG Cloud S3 Configuration
  S3_ENDPOINT_URL: "https://hcm03.vstorage.vngcloud.vn"
  S3_BUCKET_NAME: "RAG-lab-bucket"
  AWS_DEFAULT_REGION: "hcm03"
