apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
  namespace: rag-system
data:
  # ✅ Cấu hình OpenSearch
  OPENSEARCH_URL: "https://khuongnd3-opens-107444-344gj-hcm03.vdb-opensearch.vngcloud.vn:9200"
  OPENSEARCH_INDEX: "rag-assistant"

  # ✅ Cấu hình Ollama
  OLLAMA_URL: "http://ollama-service.rag-system.svc.cluster.local:11434"
  OLLAMA_MODEL: "deepseek-r1:8b"

  # ✅ Model Embedding (tiếng Việt)
  EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"

  # ✅ Thông số RAG
  RAG_TOP_K: "5"
  RAG_SCORE_THRESHOLD: "0.6"
  chunk_size: "512"
  chunk_overlap: "50"

  # ✅ Cấu hình VNG Cloud S3
  S3_ENDPOINT_URL: "https://hcm03.vstorage.vngcloud.vn"
  S3_BUCKET_NAME: "RAG-lab-bucket"
  AWS_DEFAULT_REGION: "hcm03"
