apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: rag-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        app: ollama  # Ch? ch?y trên node có label này
      tolerations:
        - key: "gpu-only"
          operator: "Exists"
          effect: "NoSchedule"
          # (Không b?t bu?c, ch? thêm n?u sau này có taint l?i)
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "4"
              memory: "8Gi"
              nvidia.com/gpu: "1"
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0"
          livenessProbe:
            httpGet:
              path: /api/tags
              port: 11434
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/tags
              port: 11434
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      initContainers:
        - name: pull-model
          image: ollama/ollama:latest
          command:
            - /bin/bash
            - -c
            - |
              ollama serve &
              sleep 10
              ollama pull deepseek-r1:8b
              pkill ollama
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0"
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-pvc
