apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-app-v3
  namespace: rag-system
  labels:
    app: rag-app-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-app-v3
  template:
    metadata:
      labels:
        app: rag-app-v3
    spec:
      nodeSelector:
        app: rag-app
      tolerations:
      - key: "rag-only"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: streamlit
        image: vcr.vngcloud.vn/107444-rover-11/rag-assistant:v3
        ports:
        - containerPort: 8501
        envFrom:
        - configMapRef:
            name: rag-config
        - secretRef:
            name: rag-secrets
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rag-service-v3
  namespace: rag-system
spec:
  type: LoadBalancer
  selector:
    app: rag-app-v3
  ports:
  - port: 80
    targetPort: 8501

