apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: rag-system
type: Opaque
stringData:  # Sử dụng stringData để tránh phải encode base64
  AWS_ACCESS_KEY_ID: "b9046fada5605574f20e71a73bfd455a"
  AWS_SECRET_ACCESS_KEY: "be017e8bea83a528f8a7fcd505fdea5b"
  OPENSEARCH_USER: "master-user"
  OPENSEARCH_PASS: "Broken@123"
  OPENSEARCH_URL: "https://khuongnd3-opens-107444-344gj-hcm03.vdb-opensearch.vngcloud.vn:9200"
  STREAMLIT_USERS: '{"admin":"admin123","user":"user123","manager":"manager234"}'
